---
- name: Creates directory
  file:
    path: /home/ubuntu/udapeople
    state: directory

- name: Extract Artifact on ec2 instance
  unarchive:
    src: "../../../../../artifact.tar.gz"
    dest: "/home/ubuntu/udapeople"


- name: Executing node
  shell: |
    cd /home/ubuntu/udapeople
    npm install
    pm2 stop default
    pm2 start npm -- start